#!/usr/bin/python
# -*- coding: utf-8 -*-

# This file is autogenerated... If you modify it,
# it will be overwritten by the next update!

OPCODES = (
    'brk', 'ora', 'asl', 'php', 'bpl', 'clc', 'jsr', 'and', 
    'bit', 'rol', 'plp', 'bmi', 'sec', 'rti', 'eor', 'lsr', 
    'pha', 'jmp', 'bvc', 'cli', 'rts', 'adc', 'ror', 'pla', 
    'bcs', 'sei', 'sta', 'sty', 'stx', 'dey', 'txa', 'bcc', 
    'tya', 'txs', 'ldy', 'lda', 'ldx', 'tay', 'tax', 'clv', 
    'tsx', 'cpy', 'cmp', 'dec', 'iny', 'dex', 'bne', 'cld', 
    'cpx', 'sbc', 'inc', 'inx', 'nop', 'beq', 'sed', 
    )

MNEMOS = (
    'brk', 'ora', None , None , None , 'ora', 'asl', None , 
    'php', 'ora', 'asl', None , None , 'ora', 'asl', None , 
    'bpl', 'ora', None , None , None , 'ora', 'asl', None , 
    'clc', 'ora', None , None , None , 'ora', 'asl', None , 
    'jsr', 'and', None , None , 'bit', 'and', 'rol', None , 
    'plp', 'and', 'rol', None , 'bit', 'and', 'rol', None , 
    'bmi', 'and', None , None , None , 'and', 'rol', None , 
    'sec', 'and', None , None , None , 'ora', 'asl', None , 
    'rti', 'eor', None , None , None , 'eor', 'lsr', None , 
    'pha', 'eor', 'lsr', None , 'jmp', 'eor', 'lsr', None , 
    'bvc', 'eor', None , None , None , 'eor', 'lsr', None , 
    'cli', 'eor', None , None , None , 'eor', 'lsr', None , 
    'rts', 'adc', None , None , None , 'adc', 'ror', None , 
    'pla', 'adc', 'ror', None , 'jmp', 'adc', 'ror', None , 
    'bcs', 'adc', None , None , None , 'adc', 'ror', None , 
    'sei', 'adc', None , None , None , 'adc', 'ror', None , 
    None , 'sta', None , None , 'sty', 'sta', 'stx', None , 
    'dey', None , 'txa', None , 'sty', 'sta', 'stx', None , 
    'bcc', 'sta', None , None , 'sty', 'sta', 'stx', None , 
    'tya', 'sta', 'txs', None , None , 'sta', None , None , 
    'ldy', 'lda', 'ldx', None , 'ldy', 'lda', 'ldx', None , 
    'tay', 'lda', 'tax', None , 'ldy', 'lda', 'ldx', None , 
    'bcs', 'lda', None , None , 'ldy', 'lda', 'ldx', None , 
    'clv', 'lda', 'tsx', None , 'ldy', 'lda', 'ldx', None , 
    'cpy', 'cmp', None , None , 'cpy', 'cmp', 'dec', None , 
    'iny', 'cmp', 'dex', None , 'cpy', 'cmp', 'dec', None , 
    'bne', 'cmp', None , None , None , 'cmp', 'dec', None , 
    'cld', 'cmp', None , None , None , 'cmp', 'dec', None , 
    'cpx', 'sbc', None , None , 'cpx', 'sbc', 'inc', None , 
    'inx', 'sbc', 'nop', None , 'cpx', 'sbc', 'inc', None , 
    'beq', 'sbc', None , None , None , 'sbc', 'inc', None , 
    'sed', 'sbc', None , None , None , 'sbc', 'inc', None , 
    )

INHERENT = 'inherent'
INDZEROX = 'indzerox'
ZEROPAGE = 'zeropage'
IMMEDIATE = 'immediate'
ACCUMULATOR = 'accumulator'
ABSOLUTE = 'absolute'
RELATIVE = 'relative'
INDZEROY = 'indzeroy'
ZEROPAGEX = 'zeropagex'
ABSOLY = 'absoly'
ABSOLX = 'absolx'
INDIRECT = 'indirect'
ZEROPAGEY = 'zeropagey'

MODES = (
    INHERENT   , INDZEROX   , None       , None       , 
    None       , ZEROPAGE   , ZEROPAGE   , None       , 
    INHERENT   , IMMEDIATE  , ACCUMULATOR, None       , 
    None       , ABSOLUTE   , ABSOLUTE   , None       , 
    RELATIVE   , INDZEROY   , None       , None       , 
    None       , ZEROPAGEX  , ZEROPAGEX  , None       , 
    INHERENT   , ABSOLY     , None       , None       , 
    None       , ABSOLX     , ABSOLX     , None       , 
    ABSOLUTE   , INDZEROX   , None       , None       , 
    ZEROPAGE   , ZEROPAGE   , ZEROPAGE   , None       , 
    INHERENT   , IMMEDIATE  , ACCUMULATOR, None       , 
    ABSOLUTE   , ABSOLUTE   , ABSOLUTE   , None       , 
    RELATIVE   , INDZEROY   , None       , None       , 
    None       , ZEROPAGEX  , ZEROPAGEX  , None       , 
    INHERENT   , ABSOLY     , None       , None       , 
    None       , ABSOLX     , ABSOLX     , None       , 
    INHERENT   , INDZEROX   , None       , None       , 
    None       , ZEROPAGE   , ZEROPAGE   , None       , 
    INHERENT   , IMMEDIATE  , ACCUMULATOR, None       , 
    ABSOLUTE   , ABSOLUTE   , ABSOLUTE   , None       , 
    RELATIVE   , INDZEROY   , None       , None       , 
    None       , ZEROPAGEX  , ZEROPAGEX  , None       , 
    INHERENT   , ABSOLY     , None       , None       , 
    None       , ABSOLX     , ABSOLX     , None       , 
    INHERENT   , INDZEROX   , None       , None       , 
    None       , ZEROPAGE   , ZEROPAGE   , None       , 
    INHERENT   , IMMEDIATE  , ACCUMULATOR, None       , 
    INDIRECT   , ABSOLUTE   , ABSOLUTE   , None       , 
    RELATIVE   , INDZEROY   , None       , None       , 
    None       , ZEROPAGEX  , ZEROPAGEX  , None       , 
    INHERENT   , ABSOLY     , None       , None       , 
    None       , ABSOLX     , ABSOLX     , None       , 
    None       , INDZEROX   , None       , None       , 
    ZEROPAGE   , ZEROPAGE   , ZEROPAGE   , None       , 
    INHERENT   , None       , INHERENT   , None       , 
    ABSOLUTE   , ABSOLUTE   , ABSOLUTE   , None       , 
    RELATIVE   , INDZEROY   , None       , None       , 
    ZEROPAGEX  , ZEROPAGEX  , ZEROPAGEY  , None       , 
    INHERENT   , ABSOLY     , INHERENT   , None       , 
    None       , ABSOLX     , None       , None       , 
    IMMEDIATE  , INDZEROX   , IMMEDIATE  , None       , 
    ZEROPAGE   , ZEROPAGE   , ZEROPAGE   , None       , 
    INHERENT   , IMMEDIATE  , INHERENT   , None       , 
    ABSOLUTE   , ABSOLUTE   , ABSOLUTE   , None       , 
    RELATIVE   , INDZEROY   , None       , None       , 
    ZEROPAGEX  , ZEROPAGEX  , ZEROPAGEY  , None       , 
    INHERENT   , ABSOLY     , INHERENT   , None       , 
    ABSOLX     , ABSOLX     , ABSOLY     , None       , 
    IMMEDIATE  , INDZEROX   , None       , None       , 
    ZEROPAGE   , ZEROPAGE   , ZEROPAGE   , None       , 
    INHERENT   , IMMEDIATE  , INHERENT   , None       , 
    ABSOLUTE   , ABSOLUTE   , ABSOLUTE   , None       , 
    RELATIVE   , INDZEROY   , None       , None       , 
    None       , ZEROPAGEX  , ZEROPAGEX  , None       , 
    INHERENT   , ABSOLY     , None       , None       , 
    None       , ABSOLX     , ABSOLX     , None       , 
    IMMEDIATE  , INDZEROX   , None       , None       , 
    ZEROPAGE   , ZEROPAGE   , ZEROPAGE   , None       , 
    INHERENT   , IMMEDIATE  , INHERENT   , None       , 
    ABSOLUTE   , ABSOLUTE   , ABSOLUTE   , None       , 
    RELATIVE   , INDZEROY   , None       , None       , 
    None       , ZEROPAGEX  , ZEROPAGEX  , None       , 
    INHERENT   , ABSOLY     , None       , None       , 
    None       , ABSOLX     , ABSOLX     , None       , 
    )

